/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CounterFeature: typeof import('./../../features/CounterFeature.vue')['default']
    PostForm: typeof import('./../../features/PostForm/ui/PostForm.vue')['default']
    PostList: typeof import('./../../features/PostList/ui/PostList.vue')['default']
  }
}
