/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonUi: typeof import('./../../shared/ui/ButtonUi/ButtonUi.vue')['default']
    CounterFeature: typeof import('./../../features/CounterFeat/ui/CounterFeature.vue')['default']
    InputUi: typeof import('./../../shared/ui/InputUi/InputUi.vue')['default']
    ModalUi: typeof import('./../../shared/ui/ModalUi/ModalUi.vue')['default']
    NavBar: typeof import('./../../widgets/NavBar/ui/NavBar.vue')['default']
    PaginationUi: typeof import('./../../shared/ui/PaginationUi/ui/PaginationUi.vue')['default']
    PostForm: typeof import('./../../features/PostForm/ui/PostForm.vue')['default']
    PostItem: typeof import('./../../entities/PostItem/ui/PostItem.vue')['default']
    PostList: typeof import('./../../features/PostList/ui/PostList.vue')['default']
    PostListContent: typeof import('../../features/PostList/ui/PostListContent/PostListMain.vue')['default']
    PostListFooter: typeof import('./../../features/PostList/ui/PostListFooter/PostListFooter.vue')['default']
    PostListHeader: typeof import('./../../features/PostList/ui/PostListHeader/PostListHeader.vue')['default']
    PostListMain: typeof import('./../../features/PostList/ui/PostListMain/PostListMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectUi: typeof import('./../../shared/ui/SelectUi/SelectUi.vue')['default']
    UiButton: typeof import('./../../shared/ui/ButtonUi/UiButton.vue')['default']
  }
}
