/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonUi: typeof import('./../../shared/ui/ButtonUi/ButtonUi.vue')['default']
    CounterFeature: typeof import('./../../features/CounterFeature.vue')['default']
    InputUi: typeof import('./../../shared/ui/InputUi/InputUi.vue')['default']
    ModalUi: typeof import('./../../shared/ui/ModalUi/ModalUi.vue')['default']
    PostForm: typeof import('./../../features/PostForm/ui/PostForm.vue')['default']
    PostItem: typeof import('./../../entities/PostItem/ui/PostItem.vue')['default']
    PostList: typeof import('./../../features/PostList/ui/PostList.vue')['default']
    SelectUi: typeof import('./../../shared/ui/SelectUi/SelectUi.vue')['default']
    UiButton: typeof import('./../../shared/ui/ButtonUi/UiButton.vue')['default']
  }
}
